language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
sudo: required
services:
  - docker

before_install:  
  - npm test
  - docker build -t khairul3232/docker-react -f Dockerfile.dev .

script:  
  - docker run khairul3232/docker-react npm run build

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-433864529669"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"