language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
sudo: required
services:
  - docker

before_install:  
  - docker build -t khairul3232/docker-react -f Dockerfile.dev .

script:
  - npm test
  - docker run -it khairul3232/docker-react npm run build